# Generated by Django 5.2.8 on 2025-11-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concepto',
            name='cantidad_cuotas',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='concepto',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
