# Generated by Django 5.2.8 on 2025-11-23 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
        ('perfiles', '0003_alter_apoderado_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('deuda_id', models.AutoField(primary_key=True, serialize=False)),
                ('pagada', models.BooleanField(default=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deudas', to='perfiles.alumno')),
                ('apoderado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deudas', to='perfiles.apoderado')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deudas', to='gestion.concepto')),
            ],
        ),
        migrations.AddField(
            model_name='registropago',
            name='deuda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='gestion.deuda'),
        ),
    ]
