# Generated by Django 5.2.8 on 2025-11-24 01:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_deuda_registropago_deuda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registropago',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
