# Generated by Django 4.2.26 on 2025-11-23 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('rut_dni', models.CharField(max_length=20, unique=True)),
                ('apoderado_id', models.AutoField(primary_key=True, serialize=False)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.TextField()),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('registrar_pago', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('rut_dni', models.CharField(max_length=20, unique=True)),
                ('alumno_id', models.AutoField(primary_key=True, serialize=False)),
                ('curso', models.CharField(max_length=100)),
                ('colegio', models.CharField(max_length=100)),
                ('apoderado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='perfiles.apoderado')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
