# Generated by Django 5.2.8 on 2025-11-23 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0003_alter_apoderado_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='rut_dni',
            field=models.CharField(max_length=20, unique=True, verbose_name='RUT-DNI'),
        ),
        migrations.AlterField(
            model_name='apoderado',
            name='rut_dni',
            field=models.CharField(max_length=20, unique=True, verbose_name='RUT-DNI'),
        ),
    ]
